### ISSUE TITLE
Add grayscale images to print

### ISSUE THREAD

**Issue by KittyGiraudel** [sturobson/Sassifaction#10]
We could make images grayscale when printing:

``` scss
@media print {
  img {
    -webkit-filter: grayscale(100%);
    -moz-filter: grayscale(100%);
    -ms-filter: grayscale(100%);
    -o-filter: grayscale(100%);
    filter: grayscale(100%);
  }
}
```

What do you think?
